FROM company/base:newest
MAINTAINER Jeff Risberg <j.s.risberg@gmail.com>

RUN mkdir -p /opt/company/bin /opt/company/lib /opt/company/conf

ENV PATH /opt/company/bin:$PATH

COPY snow/lib/snow-0.1.0.jar /opt/company/lib/

COPY snow/bin/LaunchSnowConnector /opt/company/bin/

RUN chmod a+x /opt/company/bin/LaunchSnowConnector

ENTRYPOINT [ "/opt/company/bin/LaunchSnowConnector" ]
