FROM openjdk:8-jre
MAINTAINER Jeff Risberg <j.s.risberg@gmail.com>

RUN mkdir -p /opt/company/bin /opt/company/lib /opt/company/conf

ENV PATH /opt/company/bin:$PATH

COPY base/lib/base-0.1.0.jar /opt/company/lib/
